/**
 * This import is automatically generated by Meteor-Vite while building for production.
 * It should only point to your Vite production bundle, and is perfectly safe to remove or commit.
 *
 * If you're seeing this import including any other files like the Vite plugin itself,
 * Meteor might be trying to import ESM over CommonJS. Please open an issue if this happens.
 * Shouldn't be dangerous, but it might bloat your client bundle.
**/
import 'meteor-vite/temp/stubs.js';



/**
 * These modules are automatically imported by jorgenvatle:vite-bundler.
 * You can commit these to your project or move them elsewhere if you'd like,
 * but they must be imported somewhere in your Meteor entrypoint file.
 *
 * More info: https://github.com/JorgenVatle/meteor-vite#lazy-loaded-meteor-packages
**/
import 'meteor/test:lazy';
import 'meteor/test:ts-modules/re-exports-index';
import 'meteor/test:ts-modules/export-star-from';
import 'meteor/test:stub-validation';
/** End of vite-bundler auto-imports **/

import { Cookies } from 'meteor/ostrio:cookies'

const cookies = new Cookies()
console.log('(meteor) cookies', cookies.get('meteor_login_token')) 
