name: 'Deploy Example Apps'
run-name: '🚀 Deploy Example Apps: ${{ github.event.head_commit.message || github.event.pull_request.title }}'

on:
  push:
    branches:
      - main
      - release

jobs:
  vue:
    name: 'Vue'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'vue'

  svelte:
    name: 'Svelte'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'svelte'

  react:
    name: 'React'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'react'

  solid:
    name: 'Solid'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'solid'

  vue-zodern-relay:
    name: 'Vue + zodern:relay'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'vue-zodern-relay'

  vue-ssr:
    name: 'Vue + SSR'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'vue-ssr'