name: Release Patcher
run-name: '✒️ Fix release package.json names'
on:
  pull_request:
    branches:
      - changesets/**
  push:
    branches:
      - release
      - changesets/**

concurrency: ${{ github.workflow }}-${{ github.ref }}-release-patch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Configure Git'
        run: | 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Fix package.json names using meteor package name formatting to avoid breaking npm
      - name: 'Fix package.json names'
        run: |
          npm run fix-package-name